//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using QuickComplaint.Data.Repository;
using QuickComplaint.Domain.Entities;

namespace QuickComplaint.Web.UI.Controllers
{
    public class ComplaintController : Controller
    {
        private readonly IComplaintRepository _dbComplaintRepository;
        private readonly IComplaintTypeRepository _dbComplaintTypeRepository;
        private readonly IReportingPartyRepository _dbReportingPartyRepository;
        

        public ComplaintController(IComplaintRepository dbComplaintRepository, IComplaintTypeRepository dbComplaintTypeRepository, IReportingPartyRepository dbReportingPartyRepository)
        {
            _dbComplaintRepository = dbComplaintRepository;
            _dbComplaintTypeRepository = dbComplaintTypeRepository; 
            _dbReportingPartyRepository = dbReportingPartyRepository; 
            
        }
        
        // GET: Complaint
        public ActionResult Index()
        {
            return View();
        }

        // GET: Complaint/Details/5
        [Route("Complaint/Details/{id}", Name = "GetComplaintDetails")]
        public ActionResult Details(Int32 id)
        {
            return View(_dbComplaintRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: Complaint/Create
        public ActionResult Create()
        {
            ViewBag.ComplaintTypes = new SelectList(_dbComplaintTypeRepository.GetData(), "Id", "Id");
            ViewBag.ReportingParties = new SelectList(_dbReportingPartyRepository.GetData(), "Id", "Id");
            
            return View();
        }

        // POST: Complaint/Create
        [HttpPost]
        public ActionResult Create(Complaint complaint)
        {
            try
            {
                _dbComplaintRepository.Insert(complaint);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaint);
            }
        }

        // GET: Complaint/Edit/5
        [Route("Complaint/Edit/{id}", Name = "GetComplaintEdit")]
        public ActionResult Edit(Int32 id)
        {
        	var complaint = _dbComplaintRepository.GetDataById(id).FirstOrDefault();    
            if (complaint != null) ViewBag.ComplaintTypes = new SelectList(_dbComplaintTypeRepository.GetData(), "Id", "Id", complaint.ComplaintTypeId);
            if (complaint != null) ViewBag.ReportingParties = new SelectList(_dbReportingPartyRepository.GetData(), "Id", "Id", complaint.ReportingPartyId);
            
            return View(complaint);
        }

        // POST: Complaint/Edit/5
        [Route("Complaint/Edit/{id}", Name = "PostComplaintEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 id, Complaint complaint)
        {
            try
            {
                _dbComplaintRepository.Update(complaint);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaint);
            }
        }
   }
}
