//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using QuickComplaint.Data.Repository;
using QuickComplaint.Domain.Entities;

namespace QuickComplaint.Web.UI.Controllers
{
    public class ComplaintTypeController : Controller
    {
        private readonly IComplaintTypeRepository _dbComplaintTypeRepository;
        

        public ComplaintTypeController(IComplaintTypeRepository dbComplaintTypeRepository)
        {
            _dbComplaintTypeRepository = dbComplaintTypeRepository;
            
        }
        
        // GET: ComplaintType
        public ActionResult Index()
        {
            return View();
        }

        // GET: ComplaintType/Details/5
        [Route("ComplaintType/Details/{id}", Name = "GetComplaintTypeDetails")]
        public ActionResult Details(Int32 id)
        {
            return View(_dbComplaintTypeRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: ComplaintType/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: ComplaintType/Create
        [HttpPost]
        public ActionResult Create(ComplaintType complaintType)
        {
            try
            {
                _dbComplaintTypeRepository.Insert(complaintType);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaintType);
            }
        }

        // GET: ComplaintType/Edit/5
        [Route("ComplaintType/Edit/{id}", Name = "GetComplaintTypeEdit")]
        public ActionResult Edit(Int32 id)
        {
        	var complaintType = _dbComplaintTypeRepository.GetDataById(id).FirstOrDefault();    
            
            return View(complaintType);
        }

        // POST: ComplaintType/Edit/5
        [Route("ComplaintType/Edit/{id}", Name = "PostComplaintTypeEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 id, ComplaintType complaintType)
        {
            try
            {
                _dbComplaintTypeRepository.Update(complaintType);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaintType);
            }
        }
   }
}
