//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using QuickComplaint.Data.Repository;
using QuickComplaint.Domain.Entities;

namespace QuickComplaint.Web.UI.Controllers
{
    public class ReportingPartyController : Controller
    {
        private readonly IReportingPartyRepository _dbReportingPartyRepository;
        private readonly IPhoneTypeRepository _dbPhoneTypeRepository;
        private readonly IPhoneTypeRepository _dbPhoneTypeRepository;
        

        public ReportingPartyController(IReportingPartyRepository dbReportingPartyRepository, IPhoneTypeRepository dbPhoneTypeRepository, IPhoneTypeRepository dbPhoneTypeRepository)
        {
            _dbReportingPartyRepository = dbReportingPartyRepository;
            _dbPhoneTypeRepository = dbPhoneTypeRepository; 
            _dbPhoneTypeRepository = dbPhoneTypeRepository; 
            
        }
        
        // GET: ReportingParty
        public ActionResult Index()
        {
            return View();
        }

        // GET: ReportingParty/Details/5
        [Route("ReportingParty/Details/{id}", Name = "GetReportingPartyDetails")]
        public ActionResult Details(Int32 id)
        {
            return View(_dbReportingPartyRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: ReportingParty/Create
        public ActionResult Create()
        {
            ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id");
            ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id");
            
            return View();
        }

        // POST: ReportingParty/Create
        [HttpPost]
        public ActionResult Create(ReportingParty reportingParty)
        {
            try
            {
                _dbReportingPartyRepository.Insert(reportingParty);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reportingParty);
            }
        }

        // GET: ReportingParty/Edit/5
        [Route("ReportingParty/Edit/{id}", Name = "GetReportingPartyEdit")]
        public ActionResult Edit(Int32 id)
        {
        	var reportingParty = _dbReportingPartyRepository.GetDataById(id).FirstOrDefault();    
            if (reportingParty != null) ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id", reportingParty.Phone1TypeId);
            if (reportingParty != null) ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id", reportingParty.Phone2TypeId);
            
            return View(reportingParty);
        }

        // POST: ReportingParty/Edit/5
        [Route("ReportingParty/Edit/{id}", Name = "PostReportingPartyEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 id, ReportingParty reportingParty)
        {
            try
            {
                _dbReportingPartyRepository.Update(reportingParty);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reportingParty);
            }
        }
   }
}
