//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using QuickComplaint.Data;
using QuickComplaint.Domain.Entities;
using QuickComplaint.Data.DbCommandProvider;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using Data;


namespace QuickComplaint.Data.Repository
{
    [DataObject(true)]
    public class DbComplaintTypeRepository : IComplaintTypeRepository, IDisposable
    {

        private readonly IDbComplaintTypeCommandProvider _dbComplaintTypeCommandProvider;
        private DbConnectionHolder _dbConnHolder;

        public DbComplaintTypeRepository(IDbComplaintTypeCommandProvider dbComplaintTypeCommandProvider)
        {
            _dbComplaintTypeCommandProvider = dbComplaintTypeCommandProvider;
            _dbConnHolder = _dbComplaintTypeCommandProvider.ComplaintTypeDbConnectionHolder;
        }

        /// <summary>
        /// Selects one or more records from the ComplaintType table 
        /// </summary>
        /// <returns></returns>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ICollection<ComplaintType> GetData()
        {
            var command = _dbComplaintTypeCommandProvider.GetGetDataDbCommand();
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            var entList = new Collection<ComplaintType>();
            var reader = new SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection));
            while (reader.Read())
            {
                var tempEntity = new ComplaintType(reader.GetInt32("Id"), reader.GetString("Name"));
                entList.Add(tempEntity);
            }
            reader.Close();
            return entList;

        }

        /// <summary>
        /// Updates one or more records from the ComplaintType table 
        /// </summary>
        /// <param name="name"></param>
        /// <param name="id"></param>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public void Update(string name, Int32 id)
        {
            var command = _dbComplaintTypeCommandProvider.GetUpdateDbCommand(name, id);
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            command.ExecuteNonQuery();
            _dbConnHolder.Close();
        }

        [DataObjectMethod(DataObjectMethodType.Update, false)]
        public void Update(ComplaintType complaintType)
        {
            Update(complaintType.Name, (Int32)complaintType.Id);
        }

        /// <summary>
        /// Deletes one or more records from the ComplaintType table 
        /// </summary>
        /// <param name="id"></param>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public void Delete(Int32 id)
        {
            var command = _dbComplaintTypeCommandProvider.GetDeleteDbCommand(id);
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            command.ExecuteNonQuery();
            _dbConnHolder.Close();
        }

        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public void Delete(ComplaintType complaintType)
        {
            Delete((Int32)complaintType.Id);
        }

        /// <summary>
        /// Inserts an entity of ComplaintType into the database.
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public Int32 Insert(string name)
        {
            var command = _dbComplaintTypeCommandProvider.GetInsertDbCommand(name);
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            var returnValue = Convert.ToInt32(command.ExecuteScalar());
            _dbConnHolder.Close();
            return returnValue;

        }

        [DataObjectMethod(DataObjectMethodType.Insert, false)]
        public Int32 Insert(ComplaintType complaintType)
        {
            return Insert(complaintType.Name);
        }

        /// <summary>
        /// Function GetDataPageable returns a IDataReader populated with a subset of data from ComplaintType
        /// </summary>
        /// <param name="sortExpression"></param>
        /// <param name="page"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PagedResult<ComplaintType> GetDataPageable(string sortExpression, Int32 page, Int32 pageSize)
        {
            var command = _dbComplaintTypeCommandProvider.GetGetDataPageableDbCommand(sortExpression, page, pageSize);
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            var entList = new Collection<ComplaintType>();
            var reader = new SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection));
            while (reader.Read())
            {
                var tempEntity = new ComplaintType(reader.GetInt32("Id"), reader.GetString("Name"));
                entList.Add(tempEntity);
            }
            reader.Close();
            var totalCount = GetRowCount();
            var pagedResults = new PagedResult<ComplaintType>(page, pageSize, totalCount, entList);
            return pagedResults;

        }

        /// <summary>
        /// Function GetRowCount returns the row count for ComplaintType
        /// </summary>
        /// <returns></returns>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public Int32 GetRowCount()
        {
            var command = _dbComplaintTypeCommandProvider.GetGetRowCountDbCommand();
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            var returnValue = Convert.ToInt32(command.ExecuteScalar());
            _dbConnHolder.Close();
            return returnValue;

        }

        /// <summary>
        /// Function  GetDataById returns a IDataReader for ComplaintType
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        /// <remarks></remarks>
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ICollection<ComplaintType> GetDataById(Int32 id)
        {
            var command = _dbComplaintTypeCommandProvider.GetGetDataByIdDbCommand(id);
            command.Connection = _dbConnHolder.Connection;
            _dbConnHolder.Open();
            var entList = new Collection<ComplaintType>();
            var reader = new SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection));
            while (reader.Read())
            {
                var tempEntity = new ComplaintType(reader.GetInt32("Id"), reader.GetString("Name"));
                entList.Add(tempEntity);
            }
            reader.Close();
            return entList;

        }

        #region "IDisposable Support"
        private bool disposedValue;
        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposedValue)
            {
                if (disposing)
                {
                    switch (_dbConnHolder.Connection.State)
                    {
                        case ConnectionState.Open:
                            _dbConnHolder.Close();
                            break;
                    }
                    _dbConnHolder = null;
                }
            }
            this.disposedValue = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        #endregion

    }
}
