//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Data;
using System.Data.SqlClient;
using QuickComplaint.Data.DbCommandProvider;

namespace QuickComplaint.Data.SqlDbCommandProvider
{
    public class SqlDbComplaintDetailCommandProvider : IDbComplaintDetailCommandProvider
    {
        public SqlDbComplaintDetailCommandProvider()
        {
            ComplaintDetailDbConnectionHolder = new DbConnectionHolder(DbConnectionName);
        }

        public string DbConnectionName => "QuickComplaintConnection";

        public DbConnectionHolder ComplaintDetailDbConnectionHolder { get; }

        /// <summary>
        ///     Selects one or more records from the ComplaintDetails table
        /// </summary>
        /// <returns></returns>
        /// <remarks></remarks>
        public IDbCommand GetGetDataDbCommand()
        {
            var command = new SqlCommand("ComplaintDetail_Select");
            command.CommandType = CommandType.StoredProcedure;
            command.Connection = (SqlConnection) ComplaintDetailDbConnectionHolder.Connection;
            return command;
        }

        /// <summary>
        ///     Function GetDataPageable returns a IDataReader populated with a subset of data from ComplaintDetails
        /// </summary>
        /// <param name="sortExpression" />
        /// <param name="page" />
        /// <param name="pageSize" />
        /// <returns></returns>
        /// <remarks></remarks>
        public IDbCommand GetGetDataPageableDbCommand(string sortExpression, int page, int pageSize)
        {
            var command = new SqlCommand("ComplaintDetail_GetDataPageable");
            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@sortExpression", SqlDbType.VarChar,
                sortExpression));
            command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@page", SqlDbType.Int, page));
            command.Parameters.Add(SqlParameterFactory.CreateInputParameter("@pageSize", SqlDbType.Int, pageSize));
            command.Connection = (SqlConnection) ComplaintDetailDbConnectionHolder.Connection;
            return command;
        }

        /// <summary>
        ///     Function GetRowCount returns the row count for ComplaintDetails
        /// </summary>
        /// <returns></returns>
        /// <remarks></remarks>
        public IDbCommand GetGetRowCountDbCommand()
        {
            var command = new SqlCommand("ComplaintDetail_GetRowCount");
            command.CommandType = CommandType.StoredProcedure;
            command.Connection = (SqlConnection) ComplaintDetailDbConnectionHolder.Connection;
            return command;
        }
    }
}