//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using QuickComplaint.Data.Entities;
using QuickComplaint.Data.Repository;
using QuickComplaint.Web.UI.Controllers.Api;

namespace QuickComplaint.Web.UI.Test.Controllers.Api
{
    [TestClass]
    public class ComplaintTypeApiControllerTests
    {
        private Mock<IComplaintTypeRepository> _repository;

        private readonly List<ComplaintType> _repositoryList = new List<ComplaintType>
        {
            //TODO Initialize test data
            new ComplaintType()
        };

        private ComplaintTypeApiController _target;

        [TestMethod]
        public void Delete_Should_Delete_A_ComplaintType()
        {
            _repository
                .Setup(it => it.Delete(It.IsAny<int>()))
                .Callback<int>(id =>
                {
                    var i = _repositoryList.FindIndex(q => q.Id == id);
                    _repositoryList.RemoveAt(i);
                });
            var iniCount = _repositoryList.Count();
            var result = _target.Delete(1);
            Assert.AreEqual(iniCount - 1, _repositoryList.Count());
            Assert.AreEqual(HttpStatusCode.OK, result.StatusCode);
        }

        [TestMethod]
        public void GetDataByIdTest()
        {
            _repository
                .Setup(it => it.GetDataById(It.IsAny<int>()))
                .Returns<int>(id => { return _repositoryList.Where(x => x.Id == id).ToList(); });

            var result = _target.GetDataById(idValue).ToList();
            Assert.AreEqual(_repositoryList.Where(x => x.Id == idValue).ToList().Count, result.Count);
        }

        [TestMethod]
        public void GetDataPageableTest()
        {
            PagedResult<ComplaintType> expectedResult;

            _repository
                .Setup(it => it.GetDataPageable(It.IsAny<string>(), It.IsAny<int>(), It.IsAny<int>()))
                .Returns<string, int, int>((sortExpression, page, pageSize) =>
                {
                    var query = _repositoryList;
                    switch (sortExpression)
                    {
                        case "Id":
                            query = new List<ComplaintType>(query.OrderBy(q => q.Id));
                            break;
                        case "Name":
                            query = new List<ComplaintType>(query.OrderBy(q => q.Name));
                            break;
                    }
                    return query.Take(pageSize).Skip((page - 1)*pageSize).ToList();
                });


            var result = _target.GetDataPageable("Id", 1, 2);
            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
            Assert.AreEqual(_repositoryList.Take(2).ToList().Count, expectedResult.Results.Count);
            Assert.AreEqual(_repositoryList.OrderBy(q => q.Id).FirstOrDefault().Id,
                expectedResult.Results.FirstOrDefault().Id);
        }

        [TestMethod]
        public void GetDataTest()
        {
            _repository
                .Setup(it => it.GetData())
                .Returns(_repositoryList);

            var result = _target.GetData().ToList();
            Assert.AreEqual(_repositoryList.ToList().Count, result.Count);
        }

        [TestInitialize]
        public void Init()
        {
            _repository = new Mock<IComplaintTypeRepository>();
            _target = new ComplaintTypeApiController(_repository.Object)
            {
                Request = new HttpRequestMessage {RequestUri = new Uri("http://localhost/api/ComplaintTypes")}
            };

            var config = new HttpConfiguration();

            config.MapHttpAttributeRoutes();
            config.EnsureInitialized();

            _target.Request.SetConfiguration(config);
        }

        [TestMethod]
        public void Insert_Should_Insert_A_ComplaintType()
        {
            _repository
                .Setup(it => it.Insert(It.IsAny<string>()))
                .Returns<string>(name => { _repositoryList.Add(new ComplaintType(name)); });

            //TODO insert values 
            _target.Insert(new ComplaintType(name));
            //Assert.AreEqual(11, _repositoryList.Count());
            //TODO fail until we update the test above
            Assert.Fail();
        }

        [TestMethod]
        public void Update_Should_Update_A_ComplaintType()
        {
            _repository
                .Setup(it => it.Update(It.IsAny<string>(), It.IsAny<int>()))
                .Callback<string, int>((name, id) =>
                {
                    var tComplaintType = _repositoryList.Find(x => x.Id == id);
                    tComplaintType.Name = name;
                });
            var tempComplaintType = _repositoryList.Find(x => x.Id == Id);
            var testComplaintType = new ComplaintType
            {
                Id = tempComplaintType.Id,
                Name = tempComplaintType.Name
            };

            //TODO change something on testComplaintType
            //testComplaintType.oldValue = newValue; 
            _target.Update(testComplaintType);
            //Assert.AreEqual(newValue, _repositoryList.Find(x => x.Id==1).oldValue);
            //TODO fail until we update the test above
            Assert.Fail();
        }
    }
}