//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Web.Mvc;
using QuickComplaint.Data.Entities;
using QuickComplaint.Data.Repository;

namespace QuickComplaint.Web.UI.Controllers
{
    public class ComplaintController : Controller
    {
        private readonly IComplaintRepository _dbComplaintRepository;
        private readonly IComplaintTypeRepository _dbComplaintTypeRepository;
        private readonly IReportingPartyRepository _dbReportingPartyRepository;


        public ComplaintController(IComplaintRepository dbComplaintRepository,
            IComplaintTypeRepository dbComplaintTypeRepository, IReportingPartyRepository dbReportingPartyRepository)
        {
            _dbComplaintRepository = dbComplaintRepository;
            _dbComplaintTypeRepository = dbComplaintTypeRepository;
            _dbReportingPartyRepository = dbReportingPartyRepository;
        }

        // GET: Complaint/Create
        public ActionResult Create()
        {
            ViewBag.ComplaintTypes = new SelectList(_dbComplaintTypeRepository.GetData(), "Id", "Name");
            ViewBag.ReportingParties = new SelectList(_dbReportingPartyRepository.GetData(), "Id", "Name");

            return View();
        }

        // POST: Complaint/Create
        [HttpPost]
        public ActionResult Create(Complaint complaint)
        {
            try
            {
                _dbComplaintRepository.Insert(complaint);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaint);
            }
        }

        // GET: Complaint/Details/5
        [Route("Complaint/Details/{id}", Name = "GetComplaintDetails")]
        public ActionResult Details(int id)
        {
            return View(_dbComplaintRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: Complaint/Edit/5
        [Route("Complaint/Edit/{id}", Name = "GetComplaintEdit")]
        public ActionResult Edit(int id)
        {
            var complaint = _dbComplaintRepository.GetDataById(id).FirstOrDefault();
            if (complaint != null)
                ViewBag.ComplaintTypes = new SelectList(_dbComplaintTypeRepository.GetData(), "Id", "Name",
                    complaint.ComplaintTypeId);
            if (complaint != null)
                ViewBag.ReportingParties = new SelectList(_dbReportingPartyRepository.GetData(), "Id", "Name",
                    complaint.ReportingPartyId);

            return View(complaint);
        }

        // POST: Complaint/Edit/5
        [Route("Complaint/Edit/{id}", Name = "PostComplaintEdit")]
        [HttpPost]
        public ActionResult Edit(int id, Complaint complaint)
        {
            try
            {
                _dbComplaintRepository.Update(complaint);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(complaint);
            }
        }

        // GET: Complaint
        public ActionResult Index()
        {
            return View();
        }
    }
}