//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Web.Mvc;
using QuickComplaint.Data.Entities;
using QuickComplaint.Data.Repository;

namespace QuickComplaint.Web.UI.Controllers
{
    public class ReportingPartyController : Controller
    {
        private readonly IPhoneTypeRepository _dbPhoneTypeRepository;
        private readonly IReportingPartyRepository _dbReportingPartyRepository;


        public ReportingPartyController(IReportingPartyRepository dbReportingPartyRepository,
            IPhoneTypeRepository dbPhoneTypeRepository)
        {
            _dbReportingPartyRepository = dbReportingPartyRepository;
            _dbPhoneTypeRepository = dbPhoneTypeRepository;
        }

        // GET: ReportingParty/Create
        public ActionResult Create()
        {
            ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id");
            ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Id");

            return View();
        }

        // POST: ReportingParty/Create
        [HttpPost]
        public ActionResult Create(ReportingParty reportingParty)
        {
            try
            {
                _dbReportingPartyRepository.Insert(reportingParty);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reportingParty);
            }
        }

        // GET: ReportingParty/Details/5
        [Route("ReportingParty/Details/{id}", Name = "GetReportingPartyDetails")]
        public ActionResult Details(int id)
        {
            return View(_dbReportingPartyRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: ReportingParty/Edit/5
        [Route("ReportingParty/Edit/{id}", Name = "GetReportingPartyEdit")]
        public ActionResult Edit(int id)
        {
            var reportingParty = _dbReportingPartyRepository.GetDataById(id).FirstOrDefault();
            if (reportingParty != null)
                ViewBag.PhoneTypes = new SelectList(_dbPhoneTypeRepository.GetData(), "Id", "Name",
                    reportingParty.phoneTypeId);


            return View(reportingParty);
        }

        // POST: ReportingParty/Edit/5
        [Route("ReportingParty/Edit/{id}", Name = "PostReportingPartyEdit")]
        [HttpPost]
        public ActionResult Edit(int id, ReportingParty reportingParty)
        {
            try
            {
                _dbReportingPartyRepository.Update(reportingParty);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(reportingParty);
            }
        }

        // GET: ReportingParty
        public ActionResult Index()
        {
            return View();
        }
    }
}