//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using QuickComplaint.Data.Entities;


namespace QuickComplaint.Data.Repository
{    
    public interface IComplaintRepository
    {
        ICollection<Complaint> GetData();
        void Update(Int32 complaintTypeId, string description, string locationDetails, Int32 reportingPartyId, Int32 id);
        void Update(Complaint complaint);
        void Delete(Int32 id);
        void Delete(Complaint complaint);
        Int32 Insert(Int32 complaintTypeId, string description, string locationDetails, Int32 reportingPartyId);
        Int32 Insert(Complaint complaint);
        PagedResult<Complaint> GetDataPageable(string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetRowCount();
        ICollection<Complaint> GetDataById(Int32 id);
        ICollection<Complaint> GetDataByComplaintTypeId(Int32 complaintTypeId);
        PagedResult<Complaint> GetDataByComplaintTypeIdPageable(Int32 complaintTypeId, string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetDataByComplaintTypeIdRowCount(Int32 complaintTypeId);
        ICollection<Complaint> GetDataByReportingPartyId(Int32 reportingPartyId);
        PagedResult<Complaint> GetDataByReportingPartyIdPageable(Int32 reportingPartyId, string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetDataByReportingPartyIdRowCount(Int32 reportingPartyId);
    } 
}
  