//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using QuickComplaint.Data.Entities;


namespace QuickComplaint.Data.Repository
{    
    public interface IComplaintDetailRepository
    {
        ICollection<ComplaintDetail> GetData();
        PagedResult<ComplaintDetail> GetDataPageable(string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetRowCount();
    } 
}
  