'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports QuickComplaint.Data.Entities


Namespace QuickComplaint.Data.Repository
    Public Interface IComplaintTypeRepository
        Function GetData() as ICollection(Of ComplaintType)
        Sub Update(name As String, id As Int32)
        Sub Update(complaintType as ComplaintType)
        Sub Delete(id As Int32)
        Sub Delete(complaintType as ComplaintType)
        Function Insert(name As String) as Int32
        Function Insert(complaintType as ComplaintType) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of ComplaintType)

        Function GetDataById(id As Int32) as ICollection(Of ComplaintType)
    End Interface
End NameSpace
