'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports QuickComplaint.Data
Imports QuickComplaint.Data.Entities

  
 Namespace QuickComplaint.Data.Repository     
    Public Interface IComplaintDetailRepository
        Function GetData()  as ICollection(Of ComplaintDetail)
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as PagedResult(Of ComplaintDetail)
    End Interface 
End NameSpace
  