'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports QuickComplaint.Data.Entities


Namespace QuickComplaint.Data.Repository
    Public Interface IComplaintRepository
        Function GetData() as ICollection(Of Complaint)

        Sub Update(complaintTypeId As Int32, description As String, locationDetails As String, reportingPartyId As Int32,
                   id As Int32)

        Sub Update(complaint as Complaint)
        Sub Delete(id As Int32)
        Sub Delete(complaint as Complaint)

        Function Insert(complaintTypeId As Int32, description As String, locationDetails As String,
                        reportingPartyId As Int32) as Int32

        Function Insert(complaint as Complaint) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of Complaint)

        Function GetDataById(id As Int32) as ICollection(Of Complaint)
        Function GetDataByComplaintTypeId(complaintTypeId As Int32) as ICollection(Of Complaint)

        Function GetDataByComplaintTypeIdPageable(complaintTypeId As Int32, sortExpression As String, page As Int32,
                                                  pageSize As Int32) as PagedResult(Of Complaint)

        Function GetDataByReportingPartyId(reportingPartyId As Int32) as ICollection(Of Complaint)

        Function GetDataByReportingPartyIdPageable(reportingPartyId As Int32, sortExpression As String, page As Int32,
                                                   pageSize As Int32) as PagedResult(Of Complaint)
    End Interface
End NameSpace
