//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using QuickComplaint.Data.Entities;


namespace QuickComplaint.Data.Repository
{    
    public interface IComplaintTypeRepository
    {
        ICollection<ComplaintType> GetData();
        void Update(string name, Int32 id);
        void Update(ComplaintType complaintType);
        void Delete(Int32 id);
        void Delete(ComplaintType complaintType);
        Int32 Insert(string name);
        Int32 Insert(ComplaintType complaintType);
        PagedResult<ComplaintType> GetDataPageable(string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetRowCount();
        ICollection<ComplaintType> GetDataById(Int32 id);
    } 
}
  