'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports QuickComplaint.Data.Entities


Namespace QuickComplaint.Data.Repository
    Public Interface IPhoneTypeRepository
        Function GetData() as ICollection(Of PhoneType)
        Sub Update(name As String, id As Int32)
        Sub Update(phoneType as PhoneType)
        Sub Delete(id As Int32)
        Sub Delete(phoneType as PhoneType)
        Function Insert(name As String) as Int32
        Function Insert(phoneType as PhoneType) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of PhoneType)

        Function GetDataById(id As Int32) as ICollection(Of PhoneType)
    End Interface
End NameSpace
