'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports QuickComplaint.Data.Entities


Namespace QuickComplaint.Data.Repository
    Public Interface IReportingPartyRepository
        Function GetData() as ICollection(Of ReportingParty)
        Sub Update(name As String, email As String, phone As String, phoneTypeId As Nullable(Of Int32), id As Int32)
        Sub Update(reportingParty as ReportingParty)
        Sub Delete(id As Int32)
        Sub Delete(reportingParty as ReportingParty)
        Function Insert(name As String, email As String, phone As String, phoneTypeId As Integer?) as Integer
        Function Insert(reportingParty as ReportingParty) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of ReportingParty)

        Function GetDataById(id As Int32) as ICollection(Of ReportingParty)
        Function GetDataByphoneTypeId(phoneTypeId As Int32) as ICollection(Of ReportingParty)

        Function GetDataByphoneTypeIdPageable(phoneTypeId As Int32, sortExpression As String, page As Int32,
                                              pageSize As Int32) as PagedResult(Of ReportingParty)

        Function Search(searchValue As String) as ICollection(Of ReportingParty)
    End Interface
End NameSpace
