//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using QuickComplaint.Data.Entities;


namespace QuickComplaint.Data.Repository
{    
    public interface IReportingPartyRepository
    {
        ICollection<ReportingParty> Search(string searchValue);
        ICollection<ReportingParty> GetData();
        void Update(string name, string email, string phone, Int32?  phoneTypeId, Int32 id);
        void Update(ReportingParty reportingParty);
        void Delete(Int32 id);
        void Delete(ReportingParty reportingParty);
        Int32 Insert(string name, string email, string phone, Int32?  phoneTypeId);
        Int32 Insert(ReportingParty reportingParty);
        PagedResult<ReportingParty> GetDataPageable(string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetRowCount();
        ICollection<ReportingParty> GetDataById(Int32 id);
        ICollection<ReportingParty> GetDataByPhoneTypeId(Int32 phoneTypeId);
        PagedResult<ReportingParty> GetDataByPhoneTypeIdPageable(Int32 phoneTypeId, string sortExpression, Int32 page, Int32 pageSize);
        Int32 GetDataByPhoneTypeIdRowCount(Int32 phoneTypeId);
    } 
}
  