//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace QuickComplaint.Data.Entities
{
    public class ComplaintDetail
    {
        private string _description;

        private int _id;
        private string _locationDetails;
        private string _name;
        private string _reportingParty;

        public ComplaintDetail()
        {
        }

        public ComplaintDetail(int id, string name, string description, string locationDetails, string reportingParty)
        {
            _id = id;
            _name = name;
            _description = description;
            _locationDetails = locationDetails;
            _reportingParty = reportingParty;
        }

        /// <summary>
        ///     Public Property Description
        /// </summary>
        /// <returns>Description as String</returns>
        /// <remarks></remarks>
        public virtual string Description
        {
            get { return _description; }
            set { _description = value; }
        }


        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual int Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property LocationDetails
        /// </summary>
        /// <returns>LocationDetails as String</returns>
        /// <remarks></remarks>
        public virtual string LocationDetails
        {
            get { return _locationDetails; }
            set { _locationDetails = value; }
        }

        /// <summary>
        ///     Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        ///     Public Property ReportingParty
        /// </summary>
        /// <returns>ReportingParty as String</returns>
        /// <remarks></remarks>
        public virtual string ReportingParty
        {
            get { return _reportingParty; }
            set { _reportingParty = value; }
        }
    }
}