//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace QuickComplaint.Data.Entities
{
    
    public partial class Complaint{
      
        private Int32 _id;
        private Int32 _complaintTypeId;
        private String _description;
        private String _locationDetails;
        private Int32 _reportingPartyId; 
        private ComplaintType _complaintType; 
        private ReportingParty _reportingParty;  

      public Complaint() : base()
      {
      }

      public Complaint(Int32 id, Int32 complaintTypeId, String description, String locationDetails, Int32 reportingPartyId) : base()
      {
          
           _id = id;
           _complaintTypeId = complaintTypeId;
           _description = description;
           _locationDetails = locationDetails;
           _reportingPartyId = reportingPartyId;
      }
  
    
        /// <summary>
        /// Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual Int32 Id
        {
            get{return this._id;}
            set{this._id = value;}
        }

        /// <summary>
        /// Public Property ComplaintTypeId
        /// </summary>
        /// <returns>ComplaintTypeId as Int32</returns>
        /// <remarks></remarks>
        public virtual Int32 ComplaintTypeId
        {
            get{return this._complaintTypeId;}
            set{this._complaintTypeId = value;}
        }

        /// <summary>
        /// Public Property Description
        /// </summary>
        /// <returns>Description as String</returns>
        /// <remarks></remarks>
        public virtual String Description
        {
            get{return this._description;}
            set{this._description = value;}
        }

        /// <summary>
        /// Public Property LocationDetails
        /// </summary>
        /// <returns>LocationDetails as String</returns>
        /// <remarks></remarks>
        public virtual String LocationDetails
        {
            get{return this._locationDetails;}
            set{this._locationDetails = value;}
        }

        /// <summary>
        /// Public Property ReportingPartyId
        /// </summary>
        /// <returns>ReportingPartyId as Int32</returns>
        /// <remarks></remarks>
        public virtual Int32 ReportingPartyId
        {
            get{return this._reportingPartyId;}
            set{this._reportingPartyId = value;}
        }

        public virtual ComplaintType ComplaintType 
        {
          get { return  _complaintType;}
          set { _complaintType = value;}
        }
  
      
        public virtual ReportingParty ReportingParty 
        {
          get { return  _reportingParty;}
          set { _reportingParty = value;}
        }
  
      
    }
 }     
