//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace QuickComplaint.Data.Entities
{
    public class ComplaintType
    {
        private int _id;
        private string _name;

        public ComplaintType()
        {
        }

        public ComplaintType(int id, string name)
        {
            _id = id;
            _name = name;
        }

        public virtual Collection<Complaint> Complaints { get; set; }


        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual int Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }
    }
}