//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace QuickComplaint.Data.Entities
{
    
    public partial class PhoneType{
      
        private Int32 _id;
        private String _name;
        private Collection<ReportingParty> _reportingPartiesPhone1Type;
        private Collection<ReportingParty> _reportingPartiesPhone2Type;  

      public PhoneType() : base()
      {
      }

      public PhoneType(Int32 id, String name) : base()
      {
          
           _id = id;
           _name = name;
      }
  
    
        /// <summary>
        /// Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual Int32 Id
        {
            get{return this._id;}
            set{this._id = value;}
        }

        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        public virtual Collection<ReportingParty> ReportingPartiesPhone1Type 
        {
          get { return  _reportingPartiesPhone1Type;}
          set { _reportingPartiesPhone1Type = value;}
        }
  
      
        public virtual Collection<ReportingParty> ReportingPartiesPhone2Type 
        {
          get { return  _reportingPartiesPhone2Type;}
          set { _reportingPartiesPhone2Type = value;}
        }
  
      
    }
 }     
