//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace QuickComplaint.Data.Entities
{
    public class ReportingParty
    {
        private string _email;

        private int _id;
        private string _name;
        private string _phone;
        private int? _phoneTypeId;


        public ReportingParty()
        {
        }

        public ReportingParty(int id, string name, string email, string phone, int? phoneTypeId)
        {
            _id = id;
            _name = name;
            _email = email;
            _phone = phone;
            _phoneTypeId = phoneTypeId;
        }

        public virtual Collection<Complaint> Complaints { get; set; }

        /// <summary>
        ///     Public Property Email
        /// </summary>
        /// <returns>Email as String</returns>
        /// <remarks></remarks>
        public virtual string Email
        {
            get { return _email; }
            set { _email = value; }
        }


        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual int Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        ///     Public Property phone
        /// </summary>
        /// <returns>phone as String</returns>
        /// <remarks></remarks>
        public virtual string phone
        {
            get { return _phone; }
            set { _phone = value; }
        }

        /// <summary>
        ///     Public Property phoneTypeId
        /// </summary>
        /// <returns>phoneTypeId as Int32?</returns>
        /// <remarks></remarks>
        public virtual int? phoneTypeId
        {
            get { return _phoneTypeId; }
            set { _phoneTypeId = value; }
        }


        public virtual PhoneType phoneTypePhoneType { get; set; }
    }
}