//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace QuickComplaint.Data.Entities
{
    public class ReportingParty
    {
        private string _email;

        private int _id;
        private string _name;
        private string _phone1;
        private int? _phone1TypeId;
        private string _phone2;
        private int? _phone2TypeId;

        public ReportingParty()
        {
        }

        public ReportingParty(int id, string name, string email, string phone1, int? phone1TypeId, string phone2,
            int? phone2TypeId)
        {
            _id = id;
            _name = name;
            _email = email;
            _phone1 = phone1;
            _phone1TypeId = phone1TypeId;
            _phone2 = phone2;
            _phone2TypeId = phone2TypeId;
        }

        public virtual Collection<Complaint> Complaints { get; set; }

        /// <summary>
        ///     Public Property Email
        /// </summary>
        /// <returns>Email as String</returns>
        /// <remarks></remarks>
        public virtual string Email
        {
            get { return _email; }
            set { _email = value; }
        }


        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        public virtual int Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        ///     Public Property Phone1
        /// </summary>
        /// <returns>Phone1 as String</returns>
        /// <remarks></remarks>
        public virtual string Phone1
        {
            get { return _phone1; }
            set { _phone1 = value; }
        }

        /// <summary>
        ///     Public Property Phone1TypeId
        /// </summary>
        /// <returns>Phone1TypeId as Int32?</returns>
        /// <remarks></remarks>
        public virtual int? Phone1TypeId
        {
            get { return _phone1TypeId; }
            set { _phone1TypeId = value; }
        }


        public virtual PhoneType Phone1TypePhoneType { get; set; }

        /// <summary>
        ///     Public Property Phone2
        /// </summary>
        /// <returns>Phone2 as String</returns>
        /// <remarks></remarks>
        public virtual string Phone2
        {
            get { return _phone2; }
            set { _phone2 = value; }
        }

        /// <summary>
        ///     Public Property Phone2TypeId
        /// </summary>
        /// <returns>Phone2TypeId as Int32?</returns>
        /// <remarks></remarks>
        public virtual int? Phone2TypeId
        {
            get { return _phone2TypeId; }
            set { _phone2TypeId = value; }
        }


        public virtual PhoneType Phone2TypePhoneType { get; set; }
    }
}