//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;

namespace QuickComplaint.Data.DbCommandProvider
{
    public interface IDbComplaintCommandProvider
        {
        DbConnectionHolder ComplaintDbConnectionHolder { get; }
        string DbConnectionName { get; }
        IDbCommand GetGetDataDbCommand(); 
        IDbCommand GetUpdateDbCommand(Int32 complaintTypeId, string description, string locationDetails, Int32 reportingPartyId, Int32 id); 
        IDbCommand GetDeleteDbCommand(Int32 id); 
        IDbCommand GetInsertDbCommand(Int32 complaintTypeId, string description, string locationDetails, Int32 reportingPartyId); 
        IDbCommand GetGetDataPageableDbCommand(string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetRowCountDbCommand(); 
        IDbCommand GetGetDataByIdDbCommand(Int32 id); 
        IDbCommand GetGetDataByComplaintTypeIdDbCommand(Int32 complaintTypeId); 
        IDbCommand GetGetDataByComplaintTypeIdPageableDbCommand(Int32 complaintTypeId, string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetDataByComplaintTypeIdRowCountDbCommand(Int32 complaintTypeId); 
        IDbCommand GetGetDataByReportingPartyIdDbCommand(Int32 reportingPartyId); 
        IDbCommand GetGetDataByReportingPartyIdPageableDbCommand(Int32 reportingPartyId, string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetDataByReportingPartyIdRowCountDbCommand(Int32 reportingPartyId); 
    }
}
