'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace QuickComplaint.Data.DbCommandProvider
    Public Interface IDbComplaintCommandProvider
        ReadOnly Property ComplaintDbConnectionHolder As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand

        Function GetUpdateDbCommand(complaintTypeId As Int32, description As String, locationDetails As String,
                                    reportingPartyId As Int32, id As Int32) As IDbCommand

        Function GetDeleteDbCommand(id As Int32) As IDbCommand

        Function GetInsertDbCommand(complaintTypeId As Int32, description As String, locationDetails As String,
                                    reportingPartyId As Int32) As IDbCommand

        Function GetGetDataPageableDbCommand(sortExpression As String, page As Int32, pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByIdDbCommand(id As Int32) As IDbCommand
        Function GetGetDataByComplaintTypeIdDbCommand(complaintTypeId As Int32) As IDbCommand

        Function GetGetDataByComplaintTypeIdPageableDbCommand(complaintTypeId As Int32, sortExpression As String,
                                                              page As Int32, pageSize As Int32) As IDbCommand

        Function GetGetDataByComplaintTypeIdRowCountDbCommand(complaintTypeId As Int32) As IDbCommand
        Function GetGetDataByReportingPartyIdDbCommand(reportingPartyId As Int32) As IDbCommand

        Function GetGetDataByReportingPartyIdPageableDbCommand(reportingPartyId As Int32, sortExpression As String,
                                                               page As Int32, pageSize As Int32) As IDbCommand

        Function GetGetDataByReportingPartyIdRowCountDbCommand(reportingPartyId As Int32) As IDbCommand
    End Interface
End Namespace
