//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;

namespace QuickComplaint.Data.DbCommandProvider
{
    public interface IDbPhoneTypeCommandProvider
        {
        DbConnectionHolder PhoneTypeDbConnectionHolder { get; }
        string DbConnectionName { get; }
        IDbCommand GetGetDataDbCommand(); 
        IDbCommand GetUpdateDbCommand(string name, Int32 id); 
        IDbCommand GetDeleteDbCommand(Int32 id); 
        IDbCommand GetInsertDbCommand(string name); 
        IDbCommand GetGetDataPageableDbCommand(string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetRowCountDbCommand(); 
        IDbCommand GetGetDataByIdDbCommand(Int32 id); 
    }
}
