'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace QuickComplaint.Data.DbCommandProvider
    Public Interface IDbReportingPartyCommandProvider
        ReadOnly Property ReportingPartyDbConnectionHolder() As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand
        Function GetUpdateDbCommand( ByVal name As String,  ByVal email As String,  ByVal phone1 As String,  ByVal phone1TypeId As  Nullable(Of Int32) ,  ByVal phone2 As String,  ByVal phone2TypeId As  Nullable(Of Int32) ,  ByVal id As Int32) As IDbCommand
        Function GetDeleteDbCommand( ByVal id As Int32) As IDbCommand
        Function GetInsertDbCommand( ByVal name As String,  ByVal email As String,  ByVal phone1 As String,  ByVal phone1TypeId As  Nullable(Of Int32) ,  ByVal phone2 As String,  ByVal phone2TypeId As  Nullable(Of Int32) ) As IDbCommand
        Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByIdDbCommand( ByVal id As Int32) As IDbCommand
        Function GetGetDataByPhone1TypeIdDbCommand( ByVal phone1TypeId As Int32) As IDbCommand
        Function GetGetDataByPhone1TypeIdPageableDbCommand( ByVal phone1TypeId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetDataByPhone1TypeIdRowCountDbCommand( ByVal phone1TypeId As Int32) As IDbCommand
        Function GetGetDataByPhone2TypeIdDbCommand( ByVal phone2TypeId As Int32) As IDbCommand
        Function GetGetDataByPhone2TypeIdPageableDbCommand( ByVal phone2TypeId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetDataByPhone2TypeIdRowCountDbCommand( ByVal phone2TypeId As Int32) As IDbCommand

    End Interface
End Namespace
