//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;

namespace QuickComplaint.Data.DbCommandProvider
{
    public interface IDbReportingPartyCommandProvider
        {
        DbConnectionHolder ReportingPartyDbConnectionHolder { get; }
        string DbConnectionName { get; }
        IDbCommand GetSearchDbCommand(string searchValue); 
        IDbCommand GetGetDataDbCommand(); 
        IDbCommand GetUpdateDbCommand(string name, string email, string phone, Int32?  phoneTypeId, Int32 id); 
        IDbCommand GetDeleteDbCommand(Int32 id); 
        IDbCommand GetInsertDbCommand(string name, string email, string phone, Int32?  phoneTypeId); 
        IDbCommand GetGetDataPageableDbCommand(string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetRowCountDbCommand(); 
        IDbCommand GetGetDataByIdDbCommand(Int32 id); 
        IDbCommand GetGetDataByPhoneTypeIdDbCommand(Int32 phoneTypeId); 
        IDbCommand GetGetDataByPhoneTypeIdPageableDbCommand(Int32 phoneTypeId, string sortExpression, Int32 page, Int32 pageSize); 
        IDbCommand GetGetDataByPhoneTypeIdRowCountDbCommand(Int32 phoneTypeId); 
    }
}
