//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using QuickComplaint.Data.DbCommandProvider;
using QuickComplaint.Data.Repository;
using QuickComplaint.Data.SqlDbCommandProvider;
using SimpleInjector;

namespace QuickComplaint.Web.UI
{
    public class InjectorContainerFactory
    {
        public static Container BuildSimpleInjectorContainer()
        {
            var container = new Container();


            container.Register<IDbComplaintCommandProvider, SqlDbComplaintCommandProvider>();
            container.Register<IComplaintRepository, DbComplaintRepository>();

            container.Register<IDbComplaintTypeCommandProvider, SqlDbComplaintTypeCommandProvider>();
            container.Register<IComplaintTypeRepository, DbComplaintTypeRepository>();

            container.Register<IDbPhoneTypeCommandProvider, SqlDbPhoneTypeCommandProvider>();
            container.Register<IPhoneTypeRepository, DbPhoneTypeRepository>();

            container.Register<IDbReportingPartyCommandProvider, SqlDbReportingPartyCommandProvider>();
            container.Register<IReportingPartyRepository, DbReportingPartyRepository>();


            return container;
        }
    }
}