//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using QuickComplaint.Data.DbCommandProvider;
using QuickComplaint.Data.Repository;
using QuickComplaint.Domain.Entities;

namespace QuickComplaint.Web.UI.Controllers.Api
{
    public class PhoneTypeApiController : ApiController
    {
        private readonly IPhoneTypeRepository _dbRepository;

        public PhoneTypeApiController(IPhoneTypeRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }
   
        [Route("api/phoneTypes/all", Name = "PhoneTypesGetDataRoute")]
        [HttpGet]
        public IQueryable<PhoneType> GetData() 
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/phoneTypes", Name = "PhoneTypesUpdateRoute")]
        [HttpPut]
        public void Update(PhoneType phoneType)
        {
            _dbRepository.Update( (string)phoneType.Name,  (Int32)phoneType.Id);
          }

        [Route("api/phoneTypes", Name = "PhoneTypesDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(Int32 id)
        {
            try
            {
                 _dbRepository.Delete(id);
                 return Request.CreateResponse(HttpStatusCode.OK);
            }
                 catch (Exception)
            {
                 return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/phoneTypes", Name = "PhoneTypesInsertRoute")]
        [HttpPost]
        public Int32 Insert(PhoneType phoneType)
        {
             return _dbRepository.Insert( (string)phoneType.Name);
          }

        [Route("api/phoneTypes", Name = "PhoneTypesGetDataPageableRoute")]
        [HttpGet]
        public  HttpResponseMessage  GetDataPageable(String sortExpression, Int32 page, Int32 pageSize) 
        {
            if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results =_dbRepository.GetDataPageable(sortExpression, page, pageSize);
            var totalCount = _dbRepository.GetRowCount();
            var pagedResults = new PagedResult(page, pageSize, totalCount, results);
            return Request.CreateResponse(HttpStatusCode.OK, pagedResults);
        }

        [Route("api/phoneTypes/{id}", Name = "PhoneTypesGetDataByIdRoute")]
        [HttpGet]
        public IQueryable<PhoneType> GetDataById(Int32 id) 
        {
            return _dbRepository.GetDataById(id).AsQueryable();
        }


    }
}
