//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using QuickComplaint.Data.Entities;
using QuickComplaint.Data.Repository;

namespace QuickComplaint.Web.UI.Controllers.Api
{
    public class PhoneTypeApiController : ApiController
    {
        private readonly IPhoneTypeRepository _dbRepository;

        public PhoneTypeApiController(IPhoneTypeRepository dbRepository)
        {
            _dbRepository = dbRepository;
        }

        [Route("api/phoneTypes", Name = "PhoneTypesDeleteRoute")]
        [HttpDelete]
        public HttpResponseMessage Delete(int id)
        {
            try
            {
                _dbRepository.Delete(id);
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            catch (Exception)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        [Route("api/phoneTypes/all", Name = "PhoneTypesGetDataRoute")]
        [HttpGet]
        public IQueryable<PhoneType> GetData()
        {
            return _dbRepository.GetData().AsQueryable();
        }

        [Route("api/phoneTypes/{id}", Name = "PhoneTypesGetDataByIdRoute")]
        [HttpGet]
        public IQueryable<PhoneType> GetDataById(int id)
        {
            return _dbRepository.GetDataById(id).AsQueryable();
        }

        [Route("api/phoneTypes", Name = "PhoneTypesGetDataPageableRoute")]
        [HttpGet]
        public HttpResponseMessage GetDataPageable(string sortExpression, int page, int pageSize)
        {
            if (page < 1) return Request.CreateResponse(HttpStatusCode.BadRequest);
            var results = _dbRepository.GetDataPageable(sortExpression, page, pageSize);

            return Request.CreateResponse(HttpStatusCode.OK, results);
        }

        [Route("api/phoneTypes", Name = "PhoneTypesInsertRoute")]
        [HttpPost]
        public int Insert(PhoneType phoneType)
        {
            return _dbRepository.Insert(phoneType.Name);
        }

        [Route("api/phoneTypes", Name = "PhoneTypesUpdateRoute")]
        [HttpPut]
        public void Update(PhoneType phoneType)
        {
            _dbRepository.Update(phoneType.Name, phoneType.Id);
        }
    }
}